import TranslatedDepthSeven.ProjectiveStarLocus
import TranslatedDepthSeven.RationalProjectiveLine

/-!
# Actual projective lines supplied by points of the projective star

A rational point of the equation-level projective star is a direction `z`
for which every original equation vanishes on the complete rational affine
line `h + t z`.  This file turns that equivalence into two literal geometric
containments for the actual projective subspace generated by `h` and `z`:

* the projective line is a subspace of the displayed Jacobian tangent space;
* every point of that projective line lies in the original common
  projective zero locus.

Under the explicit linear-independence hypothesis on `h` and `z`, the affine
cone over this projective subspace has dimension exactly two.
-/

namespace TranslatedDepthSeven

noncomputable section

open scoped BigOperators LinearAlgebra.Projectivization

open Finset MvPolynomial Polynomial

/-- A rational star direction satisfies every displayed rational Jacobian
row at the integral base point. -/
theorem rationalDirection_mem_tangentKernel_of_mem_integralProjectiveStarLocus
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (z : Fin n → ℚ) (hz : z ≠ 0)
    (hstar : Projectivization.mk ℚ z hz ∈
      integralProjectiveStarLocus equations degree h) :
    z ∈ equationFamilyRationalTangentKernel equations h := by
  have hline : ∀ f ∈ equations, ∀ t : ℚ,
      MvPolynomial.eval (fun i ↦ (h i : ℚ) + t * z i)
        (MvPolynomial.map (Int.castRingHom ℚ) f) = 0 :=
    (mk_mem_integralProjectiveStarLocus_iff
      equations degree h hhom z hz).1 hstar
  rw [equationFamilyRationalTangentKernel, LinearMap.mem_ker]
  funext f
  change ∑ i,
    (MvPolynomial.eval h (MvPolynomial.pderiv i f.1) : ℚ) * z i = 0
  have hpoly : rationalLinePolynomial f.1 h z = 0 :=
    Polynomial.zero_of_eval_zero _ fun t ↦ by
      rw [eval_rationalLinePolynomial]
      exact hline f.1 f.2 t
  have hcoeff := congrArg (fun q : Polynomial ℚ ↦ q.coeff 1) hpoly
  change (rationalLinePolynomial f.1 h z).coeff 1 = 0 at hcoeff
  rw [coeff_rationalLinePolynomial,
    eval_map_starCoefficient_one_eq_rationalDirectionalDerivative] at hcoeff
  exact hcoeff

/-- The rational base point itself belongs to the same displayed tangent
kernel.  The projective-star hypothesis supplies the required common-zero
condition by taking `t = 0` in the exact star equivalence. -/
theorem rationalBasePoint_mem_tangentKernel_of_mem_integralProjectiveStarLocus
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (z : Fin n → ℚ) (hz : z ≠ 0)
    (hstar : Projectivization.mk ℚ z hz ∈
      integralProjectiveStarLocus equations degree h) :
    (fun i ↦ (h i : ℚ)) ∈
      equationFamilyRationalTangentKernel equations h := by
  have hline : ∀ f ∈ equations, ∀ t : ℚ,
      MvPolynomial.eval (fun i ↦ (h i : ℚ) + t * z i)
        (MvPolynomial.map (Int.castRingHom ℚ) f) = 0 :=
    (mk_mem_integralProjectiveStarLocus_iff
      equations degree h hhom z hz).1 hstar
  apply intBasePoint_mem_equationFamilyRationalTangentKernel
    equations degree h hhom
  intro f hf
  have hroot := hline f hf 0
  simp only [zero_mul, add_zero] at hroot
  change MvPolynomial.eval (fun i ↦ (h i : ℚ))
    (MvPolynomial.map (Int.castRingHom ℚ) f) = 0 at hroot
  rw [eval_map_intCast] at hroot
  exact_mod_cast hroot

/-- The actual projective subspace generated by the base point and a
rational star direction is contained in the displayed equation-family
tangent space. -/
theorem rationalProjectiveLine_le_tangent_of_mem_integralProjectiveStarLocus
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (z : Fin n → ℚ) (hz : z ≠ 0)
    (hstar : Projectivization.mk ℚ z hz ∈
      integralProjectiveStarLocus equations degree h) :
    rationalProjectiveLine (fun i ↦ (h i : ℚ)) z ≤
      equationFamilyRationalProjectiveTangentSpace equations h := by
  have hh :=
    rationalBasePoint_mem_tangentKernel_of_mem_integralProjectiveStarLocus
      equations degree h hhom z hz hstar
  have hzTan :=
    rationalDirection_mem_tangentKernel_of_mem_integralProjectiveStarLocus
      equations degree h hhom z hz hstar
  intro P hP
  obtain ⟨a, b, hab, rfl⟩ :=
    (mem_rationalProjectiveLine_iff_exists_representation
      (fun i ↦ (h i : ℚ)) z P).mp hP
  rw [mk_mem_equationFamilyRationalProjectiveTangentSpace_iff]
  exact (equationFamilyRationalTangentKernel equations h).add_mem
    ((equationFamilyRationalTangentKernel equations h).smul_mem a hh)
    ((equationFamilyRationalTangentKernel equations h).smul_mem b hzTan)

/-- Every rational vector in the span of the base point and a rational star
direction satisfies all the original homogeneous equations. -/
theorem rationalSpanPoint_mem_cone_of_mem_integralProjectiveStarLocus
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (z : Fin n → ℚ) (hz : z ≠ 0)
    (hstar : Projectivization.mk ℚ z hz ∈
      integralProjectiveStarLocus equations degree h)
    (a b : ℚ) :
    (fun i ↦ a * (h i : ℚ) + b * z i) ∈
      integralAffineConeZeroSetOver ℚ equations := by
  have hline : ∀ f ∈ equations, ∀ t : ℚ,
      MvPolynomial.eval (fun i ↦ (h i : ℚ) + t * z i)
        (MvPolynomial.map (Int.castRingHom ℚ) f) = 0 :=
    (mk_mem_integralProjectiveStarLocus_iff
      equations degree h hhom z hz).1 hstar
  intro f hf
  let fℚ := MvPolynomial.map (Int.castRingHom ℚ) f
  have hfℚ : fℚ.IsHomogeneous (degree f) := (hhom f hf).map _
  by_cases ha : a = 0
  · subst a
    have hzCone : MvPolynomial.eval z fℚ = 0 := by
      have hpoly : rationalLinePolynomial f h z = 0 :=
        Polynomial.zero_of_eval_zero _ fun t ↦ by
          rw [eval_rationalLinePolynomial]
          exact hline f hf t
      have hlead := congrArg
        (fun q : Polynomial ℚ ↦ q.coeff (degree f)) hpoly
      change (rationalLinePolynomial f h z).coeff (degree f) = 0 at hlead
      rw [coeff_rationalLinePolynomial,
        starCoefficient_eq_of_isHomogeneous f h (degree f) (hhom f hf)] at hlead
      exact hlead
    have hscaled := eval_smul_of_isHomogeneous fℚ z b (degree f) hfℚ
    simpa [fℚ, hzCone] using hscaled
  · have hratio :
        MvPolynomial.eval (fun i ↦ (h i : ℚ) + (b / a) * z i) fℚ = 0 :=
      hline f hf (b / a)
    have hvectors :
        (fun i ↦ a * (h i : ℚ) + b * z i) =
          (fun i ↦ a * ((h i : ℚ) + (b / a) * z i)) := by
      funext i
      field_simp [ha]
    rw [hvectors, eval_smul_of_isHomogeneous fℚ
      (fun i ↦ (h i : ℚ) + (b / a) * z i) a (degree f) hfℚ]
    rw [hratio, mul_zero]

/-- Pointwise projective form: the complete actual projective line generated
by the base point and a rational star direction lies in the original common
projective zero locus. -/
theorem rationalProjectiveLine_subset_cone_of_mem_integralProjectiveStarLocus
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (z : Fin n → ℚ) (hz : z ≠ 0)
    (hstar : Projectivization.mk ℚ z hz ∈
      integralProjectiveStarLocus equations degree h) :
    (rationalProjectiveLine (fun i ↦ (h i : ℚ)) z :
        Set (Projectivization ℚ (Fin n → ℚ))) ⊆
      integralProjectiveConeZeroSetOver ℚ equations := by
  intro P hP
  obtain ⟨a, b, hab, rfl⟩ :=
    (mem_rationalProjectiveLine_iff_exists_representation
      (fun i ↦ (h i : ℚ)) z P).mp hP
  rw [mk_mem_integralProjectiveConeZeroSetOver_iff
    equations degree hhom _ hab]
  simpa [Pi.smul_apply] using
    (rationalSpanPoint_mem_cone_of_mem_integralProjectiveStarLocus
      equations degree h hhom z hz hstar a b)

/-- Under the explicit independence hypothesis, the affine cone over the
star-supplied projective line has dimension exactly two. -/
theorem finrank_starProjectiveLineCone_eq_two
    {n : ℕ} (h : IntVector n) (z : Fin n → ℚ)
    (hlin : LinearIndependent ℚ ![(fun i ↦ (h i : ℚ)), z]) :
    Module.finrank ℚ
        (rationalProjectiveLineCone (fun i ↦ (h i : ℚ)) z) = 2 :=
  finrank_rationalProjectiveLineCone_eq_two _ _ hlin

/-- Combined form of the two geometric containments and the dimension
statement. -/
theorem projectiveStarPoint_supplies_projectiveLine
    {n : ℕ} (equations : Finset (MvPolynomial (Fin n) ℤ))
    (degree : MvPolynomial (Fin n) ℤ → ℕ) (h : IntVector n)
    (hhom : ∀ f ∈ equations, f.IsHomogeneous (degree f))
    (z : Fin n → ℚ) (hz : z ≠ 0)
    (hstar : Projectivization.mk ℚ z hz ∈
      integralProjectiveStarLocus equations degree h)
    (hlin : LinearIndependent ℚ ![(fun i ↦ (h i : ℚ)), z]) :
    rationalProjectiveLine (fun i ↦ (h i : ℚ)) z ≤
        equationFamilyRationalProjectiveTangentSpace equations h ∧
      (rationalProjectiveLine (fun i ↦ (h i : ℚ)) z :
          Set (Projectivization ℚ (Fin n → ℚ))) ⊆
        integralProjectiveConeZeroSetOver ℚ equations ∧
      Module.finrank ℚ
        (rationalProjectiveLineCone (fun i ↦ (h i : ℚ)) z) = 2 := by
  exact ⟨
    rationalProjectiveLine_le_tangent_of_mem_integralProjectiveStarLocus
      equations degree h hhom z hz hstar,
    rationalProjectiveLine_subset_cone_of_mem_integralProjectiveStarLocus
      equations degree h hhom z hz hstar,
    finrank_starProjectiveLineCone_eq_two h z hlin⟩

end

end TranslatedDepthSeven
